frames: 
  window_size: 1 
  tolerance_region: 0 
  samples_per_window: 1 
  step_size: 1
  data_ndim: 3 
  shuffle:  False
  patch_type: "relative"
  patch_h: 1
  patch_w: 1
  temporal_sample_interval: 2
  MAX_BUFFER_SIZE: 1

frames_w_temp: 
  window_size: 1 
  tolerance_region: 0
  samples_per_window: 1 
  step_size: 1
  data_ndim: 3 
  shuffle:  False
  patch_type: "relative"
  patch_h: 1
  patch_w: 1
  temporal_sample_interval: 1
  MAX_BUFFER_SIZE: 1

sliding_window: 
  window_size: 16 
  tolerance_region: 7
  samples_per_window: 16 
  step_size: 8
  data_ndim: 4 
  shuffle: False
  patch_type: "relative"
  patch_h: 1
  patch_w: 1 
  temporal_sample_interval: 2
  MAX_BUFFER_SIZE: 1

sliding_window_ti8: 
  window_size: 16 
  tolerance_region: 7
  samples_per_window: 16 
  step_size: 1
  data_ndim: 4 
  shuffle: False
  patch_type: "relative"
  patch_h: 1
  patch_w: 1
  temporal_sample_interval: 8
  MAX_BUFFER_SIZE: 1

sliding_window_w_temp: 
  window_size: 16 
  tolerance_region: 7
  samples_per_window: 16 
  step_size: 8
  data_ndim: 4 
  shuffle: False
  patch_type: "relative"
  patch_h: 1
  patch_w: 1
  temporal_sample_interval: 1
  MAX_BUFFER_SIZE: 1

sliding_window_w_stride: 
  window_size: 16 
  tolerance_region: 7
  samples_per_window: 16 
  step_size: 16
  data_ndim: 4 
  shuffle: False
  patch_type: "relative"
  patch_h: 1
  patch_w: 1
  temporal_sample_interval: 2
  MAX_BUFFER_SIZE: 1

fix_patched_224: 
  window_size: 1 
  tolerance_region: 0
  samples_per_window: 1 
  step_size: 1
  data_ndim: 4 
  shuffle:  False
  patch_type: "absolute"
  patch_h: 224
  patch_w: 224
  temporal_sample_interval: 2
  MAX_BUFFER_SIZE: 1

fix_patched_512: 
  window_size: 1 
  tolerance_region: 0
  samples_per_window: 1 
  step_size: 1
  data_ndim: 4 
  shuffle:  False
  patch_type: "absolute"
  patch_h: 512
  patch_w: 512
  temporal_sample_interval: 2
  MAX_BUFFER_SIZE: 1

# Sliding styles for the test set
# Idea: You want the sliding style to be the same regardless of the training style. Specifically, you want to predict 
# the label for every single frame from a user's perspective.
test_frames: 
  window_size: 1 
  tolerance_region: 0 
  samples_per_window: 1 
  step_size: 1
  data_ndim: 3 
  shuffle:  False
  patch_type: "relative"
  patch_h: 1
  patch_w: 1
  temporal_sample_interval: 1
  MAX_BUFFER_SIZE: 1

test_sliding_window:
  window_size: 16 
  tolerance_region: 0
  samples_per_window: 16 
  step_size: 1
  data_ndim: 4 
  shuffle: False
  patch_type: "relative"
  patch_h: 1
  patch_w: 1 
  temporal_sample_interval: 1
  MAX_BUFFER_SIZE: 1

test_sliding_window_ti8:
  window_size: 16 
  tolerance_region: 0
  samples_per_window: 16 
  step_size: 1
  data_ndim: 4 
  shuffle: False
  patch_type: "relative"
  patch_h: 1
  patch_w: 1
  temporal_sample_interval: 8
  MAX_BUFFER_SIZE: 1

test_fix_patched_512: 
  window_size: 1 
  tolerance_region: 0
  samples_per_window: 1 
  step_size: 1
  data_ndim: 4 
  shuffle:  False
  patch_type: "absolute"
  patch_h: 512
  patch_w: 512
  temporal_sample_interval: 1
  MAX_BUFFER_SIZE: 1