fishfollow: 
  doi: https://doi.org/10.7910/DVN/QN66Z8
  path: '/share/j_sun/jth264/mikev3'
  precomputed_path: '/share/j_sun/jth264/precomputed/fishfollow'
  label_type: onehot
  categories: 
    - Other behavior
    - Medium bites
    - High bites
    - Traversing/swimming
    - Departure
    - Cleaner wrasse
    - Low bites
    - Change in Focal Fish
    - Solo foraging/swimming
    - Seafloor bites
    - Aggressive on focal
    - Social foraging/swimming
    - Sand rubbing
    - Not visible
    - Foraging
    - Idle
    - Coral habitat
    - Rubble habitat
    - Aggressive by focal
    - Sand habitat

  splits:
    train:
      sliding_styles:
        - frames
        - frames_w_temp
        - sliding_window
        - sliding_window_w_temp
        - sliding_window_w_stride
        - sliding_window_ti8
        - fix_patched_512
    val:
      sliding_styles:
        - frames
        - frames_w_temp
        - sliding_window
        - sliding_window_w_temp
        - sliding_window_w_stride
        - sliding_window_ti8
        - fix_patched_512
    test:
      sliding_styles:
        - test_frames
        - test_sliding_window
        - test_sliding_window_ti8
        - test_fix_patched_512

coralcam: 
  doi: https://doi.org/10.7910/DVN/BRCPIG
  path: '/share/j_sun/jth264/coralcam/organized'
  precomputed_path: '/share/j_sun/jth264/precomputed/coralcam'
  label_type: onehot
  categories: 
      - mouth not visible
      - feeding
      - charging
      - being charged
      - cturn
  splits:
    train:
      sliding_styles:
        - frames
        - frames_w_temp
        - sliding_window
        - sliding_window_w_temp
        - sliding_window_w_stride
        - sliding_window_ti8
    val:
      sliding_styles:
        - frames
        - frames_w_temp
        - sliding_window
        - sliding_window_w_temp
        - sliding_window_w_stride
        - sliding_window_ti8
    test:
      sliding_styles:
        - test_frames
        - test_sliding_window
        - test_fix_patched_512
        - test_sliding_window_ti8

ucf101: 
  path: 'you_path'
  precomputed_path: 'you_path'
  label_type: onehot
  categories: 
    - ApplyEyeMakeup
    - Archery
    - BalanceBeam
    - BaseballPitch
    - BasketballDunk
    - ApplyLipstick
    - BabyCrawling
    - BandMarching
    - Basketball
    - BenchPress

  splits:
    train:
      sliding_styles:
        - frames
        - frames_w_temp
        - sliding_window
        - sliding_window_w_temp
        - sliding_window_w_stride
    val:
      sliding_styles:
        - frames
        - frames_w_temp
        - sliding_window
        - sliding_window_w_temp
        - sliding_window_w_stride
    test:
      sliding_styles:
        - test_frames
        - test_sliding_window
  
