mike: 
  path: 'you_path'
  precomputed_path: 'you_path'
  splits:
    train:
      sliding_styles:
        - frames
        - frames_w_temp
        - sliding_window
        - sliding_window_w_temp
        - sliding_window_w_stride
        - fix_patched_512
    val:
      sliding_styles:
        - frames
        - frames_w_temp
        - sliding_window
        - sliding_window_w_temp
        - sliding_window_w_stride
        - fix_patched_512
    test:
      sliding_styles:
        - test_frames
        - test_sliding_window
        - test_fix_patched_512

abby: 
  path: 'you_path'
  precomputed_path: 'you_path'
  splits:
    train:
      sliding_styles:
        - frames
        - frames_w_temp
        - sliding_window
        - sliding_window_w_temp
        - sliding_window_w_stride
    val:
      sliding_styles:
        - frames
        - frames_w_temp
        - sliding_window
        - sliding_window_w_temp
        - sliding_window_w_stride
    test:
      sliding_styles:
        - test_frames
        - test_sliding_window
        - test_fix_patched_512