- id: vjepa2_vjepa2_attention_uniform_coralcam_sliding_window_w_temp
  dataset: coralcam
  sliding_style: sliding_window_w_temp
  backbone: vjepa2
  pooling: vjepa2_attention
  classifier: linear
  weight_config:
    weight_method: uniform
  weight_decay: 0.001
  sampler: balanced
  fulltune: true
  freeze_backbone: true
  epochs: 40
  learning_rate: 5.0e-05
  batch_size: 32
  optimizer: adam
  shuffle: false
  monitor: val_mAP
  label_type: onehot
  max_samples_per_class: 1000
  train_subset: null
  val_subset: null
  parameters: 337524101
- id: vjepa2_vjepa2_attention_focal_loss_coralcam_sliding_window_w_temp
  dataset: coralcam
  sliding_style: sliding_window_w_temp
  backbone: vjepa2
  pooling: vjepa2_attention
  classifier: linear
  weight_config:
    weight_method: focal_loss
    focal_loss_gamma: 5.0
    focal_loss_alpha: 0.75
  weight_decay: 0.001
  sampler: balanced
  fulltune: true
  freeze_backbone: true
  epochs: 40
  learning_rate: 5.0e-05
  batch_size: 32
  optimizer: adam
  shuffle: false
  monitor: val_mAP
  label_type: onehot
  max_samples_per_class: 1000
  train_subset: null
  val_subset: null
  parameters: 337524101
